# Fastlane

lane :release do
  sync_code_signing(type: "appstore")

  disable_automatic_code_signing(path: "Colorwaver.xcodeproj")
  build_app(scheme: "Colorwaver",
            workspace: "Colorwaver.xcworkspace")
  enable_automatic_code_signing(path: "Colorwaver.xcodeproj")

  upload_to_app_store
end
