# Fastlane

lane :bump do
  increment_version_code(
    gradle_file_path: "app/build.gradle",
  )
end

lane :beta do
  gradle(task: "clean bundleRelease")
  upload_to_play_store(track: 'beta')
end

lane :release do
  gradle(task: "clean bundleRelease")
  upload_to_play_store
end
